# Bash aliases that are installed into the dev container.

# Change the database used for FarmData2
setDB ()
{
  cd ~/FarmData2/docker
  ./setDB.bash $1
}

# Clear the drupal cache in the fd2_farmdata2 container.
alias clearDrupalCache="docker exec -it fd2_farmdata2 drush cc all"

# Alias codium for running VSCodium with no-sandbox.
codium ()
{
  /usr/bin/codium --no-sandbox $@
}

# Alias for running the test script
test_runner ()
{
  cd ~/FarmData2/farmdata2_modules
  ./test_runner.bash $1
}
