<?php
/**
 * @file
 * Tab Test module.
 */

 function tab_test_permission() {
   return array(
     'view tab test' => array(
       'title' => t('View tab_test'),
     ),
     'configure tab test' => array(
       'title' => t('Configure tab_test'),
     ),
   );
 }

 function tab_test_farm_access_perms($role) {
   $perms = array();

   // Load the list of farm roles.
   $roles = farm_access_roles();

   // If this role has 'edit' access, allow them to see these tabs.
   if (!empty($roles[$role]['access']['edit'])) {
     $perms[] = 'view tab test';
   }

   // If this role has 'config' access, allow them to also configure tab test.
   if (!empty($roles[$role]['access']['config'])) {
     $perms[] = 'configure tab test';
   }

   return $perms;
 }

 /**
 * Implements hook_menu().
 */
function tab_test_menu() {
  $items = array();

  $items['farm/tabs'] = array(
    'title' => 'Tabs',
    'page callback' => 'tab_test_view',
    'page arguments' => array('one','uno'),
    'access arguments' => array('view tab test'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['farm/tabs/info'] = array(
    'title' => 'Info',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );
  $items['farm/tabs/info2'] = array(
    'title' => 'Info2',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'tab_test_view',
    'page arguments' => array('two','dos'),
    'access arguments' => array('view tab test'),
    'weight' => 100,
  );

  return $items;
};

// Changes to the callback functions below are live.  
// The function for the callback set above requires a module off/on cycle.

function tab_test_view($a,$b) {
  return t("$a and $b and more stuff");
};
