version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql:delegated'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:dev
    volumes:
      - './www:/var/www/html:delegated'
      - './demoData:/demoData:delegated'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
        PMA_HOST: "db"
    restart: always
    ports:
     - 8181:80
    volumes:
     - /sessions
    links:
     - 'db'