<?php
/**
 * @file
 * FarmData2 School module.
 * See the README.md file in the fd2_example directory for more information.
 */

 function fd2_school_permission() {
   return array(
     'view fd2 school' => array(
       'title' => t('View FD2 School'),
     ),
     'configure fd2 school' => array(
       'title' => t('Configure FD2 School'),
     ),
   );
 }

 function fd2_school_farm_access_perms($role) {
   $perms = array();

   // Load the list of farm roles.
   $roles = farm_access_roles();

   // If this role has 'edit' access, allow them to see the School tab.
   if (!empty($roles[$role]['access']['edit'])) {
     $perms[] = 'view fd2 school';
   }

   // If this role has 'config' access, it to configure the fd2_school module.
   if (!empty($roles[$role]['access']['config'])) {
     $perms[] = 'configure fd2 school';
   }

   return $perms;
 }

 /**
 * Implements hook_menu() which places the School tab in the Farm
 * menu at the top of the FarmData2 page with the Dashboard.
 */
function fd2_school_menu() {
  $items = array();

  // Define the tab for the module.
  $items['farm/fd2-school'] = array(                 // Put the school in the farm menu
    'title' => 'FD2 School',                         // Put FD2 School on the tab
    'page callback' => 'fd2_school_view',            // The function that will provide the content
    'page arguments' => array('info'),               // The html file with the default content for the tab
    'access arguments' => array('view fd2 school'),  // permissions required to view the tab
    'type' => MENU_LOCAL_TASK,                        // Put it on the menu
    'weight' => -30,                                  // larger weights appear further right.
  );

  // Define the name and URL for the default sub-tab that appears when the tab is opened.
  // Content for this default sub-tab is provided by the 'page arguments' above.
  $items['farm/fd2-school/info'] = array(
    'title' => 'Info',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );

  // Add items blocks for new sub-tabs here.

  return $items;
};

// This function Loads the content for the sub-tab from the html file specified in the arguemnt.
// It must be renamed in each module.
function fd2_school_view($subtab_content) {
  $dir=dirname(__FILE__);
  $html=$dir."/".$subtab_content."/".$subtab_content.".html";
  $code=file_get_contents($html);
  return $code;
};

function fd2_school_preprocess_page() {
  $alias = drupal_get_path_alias(current_path());
  $path = implode("\n",array('farm/fd2-school*',));

  if (drupal_match_path($alias, $path)) {
    // Include the external JS libraries that are used here so they are cached by drupal.
    drupal_add_js('https://unpkg.com/vue@2.6.14/dist/vue.min.js','external');
    drupal_add_js('https://unpkg.com/axios@0.24.0/dist/axios.min.js','external');
    drupal_add_js('https://unpkg.com/dayjs@1.8.21/dayjs.min.js', 'external');

    // Define some useful variables in the JavaScript for page.
    // the @ symbol surpresses the warning when a user attempts to access a page without being logged in
    global $user;
    @$cmd="var fd2UserID=".$user->uid."; var fd2UserName='".$user->name."';";
    drupal_add_js($cmd,'inline');
  }
};
