<?php
/**
 * @file
 * FarmData2 Field Kit module.
 * See the README.md file in the directory for more information.
 */

 function fd2_field_kit_permission() {
   return array(
     'view fd2 field kit' => array(
       'title' => t('View FD2 Field Kit'),
     ),
     'configure fd2 field kit' => array(
       'title' => t('Configure FD2 Field Kit'),
     ),
   );
 }

 function fd2_field_kit_farm_access_perms($role) {
   $perms = array();

   // Load the list of farm roles.
   $roles = farm_access_roles();

   // If this role has 'edit' access, allow them to use the field kit.
   if (!empty($roles[$role]['access']['edit'])) {
     $perms[] = 'view fd2 field kit';
   }

   // If this role has 'config' access, it to configure the field kit.
   if (!empty($roles[$role]['access']['config'])) {
     $perms[] = 'configure fd2 field kit';
   }

   return $perms;
 }

 /**
 * Implements hook_menu().
 */
function fd2_field_kit_menu() {
  $items = array();

  $items['farm/fd2-field-kit'] = array(
    'title' => 'FieldKit',
    'page callback' => 'fd2_field_kit_view',
    'page arguments' => array('info.html'),
    'access arguments' => array('view fd2 field kit'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -20,
  );

  $items['farm/fd2-field-kit/info'] = array(
    'title' => 'Info',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );

  $items['farm/fd2-field-kit/seedingInput'] = array(
    'title' => 'Seeding Input',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_field_kit_view',
    'page arguments' => array('seedingInput.html'),
    'access arguments' => array('view fd2 field kit'),
    'weight' => 100,
  );

  return $items;
};

// Loads the content for the tab from the html
// file specified in the arguemnt.
function fd2_field_kit_view($form_content) {
  $dir=dirname(__FILE__);
  $html=$dir."/".$form_content;
  $code=file_get_contents($html);
  return $code;
};

function fd2_field_kit_preprocess_page() {
  $alias = drupal_get_path_alias(current_path());
  $path = implode("\n",array('farm/fd2-field-kit*',));

  if (drupal_match_path($alias, $path)) {
    // Include the external JS libraries that are used here so they are cached by drupal.
    drupal_add_js('https://unpkg.com/vue/dist/vue.min.js','external');
    drupal_add_js('https://unpkg.com/axios/dist/axios.min.js','external');
    drupal_add_js('https://unpkg.com/dayjs@1.8.21/dayjs.min.js', 'external');

    // Define some useful variables in the JavaScript for page.
    global $user;
    $cmd="var fd2UserID=".$user->uid."; var fd2UserName='".$user->name."';";
    drupal_add_js($cmd,'inline');
  }
};