FROM farmdata2/vnc
# Original Source: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt

# Install basic tools
#  VSCode, gEdit, nano, 
#  Meld
#  git
#  npm, node.js
#  browsers (chrome, firefox)

# Create a non-root user

# Cypress

