<?php
/**
 * @file
 * FarmData2 Example module.
 * See the README.md file in the fd2_example directory for more information.
 */

function fd2_example_permission() {
  return array(
    'view fd2 example' => array(
        'title' => t('View FD2 Example'),
    ),
    'configure fd2 Example' => array(
        'title' => t('Configure FD2 Example'),
    ),
  );
}

function fd2_example_farm_access_perms($role) {
  $perms = array();

   // Load the list of farm roles.
  $roles = farm_access_roles();

   // If this role has 'edit' access, allow them to see the Example tab.
  if (!empty($roles[$role]['access']['edit'])) {
    $perms[] = 'view fd2 example';
  }

   // If this role has 'config' access, it to configure the fd2_example module.
  if (!empty($roles[$role]['access']['config'])) {
    $perms[] = 'configure fd2 example';
  }

  return $perms;
}

/**
 * Implements hook_menu() which places the Exmple tab in the Farm
 * menu at the top of the FarmData2 page with the Dashboard.
 */
function fd2_example_menu() {
  $items = array();

  // Define the tab for the module.
  $items['farm/fd2-example'] = array(                 // Put the example in the farm menu
    'title' => 'FD2 Example',                         // Put FD2 Example on the tab
    'page callback' => 'fd2_example_view',            // The function that will provide the content
    'page arguments' => array('info'),                // The html file with the default content for the tab
    'access arguments' => array('view fd2 example'),  // permissions required to view the tab
    'type' => MENU_LOCAL_TASK,                        // Put it on the menu
    'weight' => -30,                                  // larger weights appear further right.
  );

  // Define the name and URL for the default sub-tab that appears when the tab is opened.
  // Content for this default sub-tab is provided by the 'page arguments' above.
  $items['farm/fd2-example/info'] = array(
    'title' => 'Info',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );

  // Add a sub-tab to the FD2 Example tab.
  // Use this block as a model for each new sub-tab that is added.
  // Note: The drupal cache must be flushed before a newly added sub-tab will appear.
  $items['farm/fd2-example/vars'] = array(
    'title' => 'Vars',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_example_view',
    'page arguments' => array('vars'),
    'access arguments' => array('view fd2 example'),
    'weight' => 100,
  );

  $items['farm/fd2-example/maps'] = array(
    'title' => 'Maps',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_example_view',
    'page arguments' => array('maps'),
    'access arguments' => array('view fd2 example'),
    'weight' => 105,
  );

  $items['farm/fd2-example/api'] = array(
    'title' => 'API',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_example_view',
    'page arguments' => array('api'),
    'access arguments' => array('view fd2 example'),
    'weight' => 110,
  );

  $items['farm/fd2-example/cache'] = array(
    'title' => 'Cache',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_example_view',
    'page arguments' => array('cache'),
    'access arguments' => array('view fd2 example'),
    'weight' => 115,
  );

  $items['farm/fd2-example/ui'] = array(
    'title' => 'UI',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_example_view',
    'page arguments' => array('ui'),
    'access arguments' => array('view fd2 example'),
    'weight' => 120,
  );

  $items['farm/fd2-example/dbtest'] = array(
    'title' => 'dbtest',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'fd2_example_view',
    'page arguments' => array('dbtest'),
    'access arguments' => array('view fd2 example'),
    'weight' => 125,
  );

  return $items;
};

// This function Loads the content for the sub-tab from the html file specified in the arguemnt.
// It must be renamed in each module.
function fd2_example_view($subtab_content) {
  $dir=dirname(__FILE__);
  $html=$dir."/".$subtab_content."/".$subtab_content.".html";
  $code=file_get_contents($html);
  return $code;
};

function fd2_example_preprocess_page() {
  $alias = drupal_get_path_alias(current_path());
  $path = implode("\n",array('farm/fd2-example*',));

  if (drupal_match_path($alias, $path)) {
    // Include the external JS libraries that are used here so they are cached by drupal.
    drupal_add_js('https://unpkg.com/vue@2.6.14/dist/vue.min.js','external');
    drupal_add_js('https://unpkg.com/axios@0.24.0/dist/axios.min.js','external');
    drupal_add_js('https://unpkg.com/dayjs@1.8.21/dayjs.min.js', 'external');

    // Define some useful variables in the JavaScript for page.
    // the @ symbol surpresses the warning when a user attempts to access a page without being logged in
    global $user;
    @$cmd="var fd2UserID=".$user->uid."; var fd2UserName='".$user->name."';";
    drupal_add_js($cmd,'inline');
  }
};