<?php

function vue_test_block_view($delta = '') {
  switch ($delta) {
    case 'vue_test':
      $block["subject"] = t('Testing Vue Integration');
      if (user_access('access content')) {
        // Retrieve and process data here.
	$script=__FILE__;
	$html=substr($script,0,-6)."html";
	$code=file_get_contents($html);
        $block["content"] = $code;
      }
      return $block;
  }
}

/**
 * Implements hook_block_info().
 */
function vue_test_block_info() {
  $blocks['vue_test'] = array(
    // The name that will appear in the block list.
    'info' => t('Test Vue Content'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_help().
 *
 * Displays help and module information for vue_test module.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function vue_test_help($path, $arg) {
  switch ($path) {
    case "admin/help#vue_test":
      return t("A test module to figure out how to use Vue.js"); 
      break; 
  }
}
